### ISSUE TITLE
Canvas width and height getting smaller on zoom level change

### ISSUE THREAD

**Issue by IsaEs** [LottieFiles/dotlottie-web#137]
## Overview

I am using @lottiefiles/dotlottie-react 0.3.1 

import myLottie from '@/assets/myLottie.lottie?url'

<DotLottieReact
  width={'600'}
  height={'400'}
  src={myLottie}
  autoplay
  loop
/>

Canvas width and height getting smaller when I change zoom level. and hits zero eventually.

- [ ] Add the `Type: Bug` label to this issue.

https://github.com/LottieFiles/dotlottie-web/blob/826f79177e6112aa3938b3c1f4b7204a7da589f4/packages/web/src/dotlottie.ts#L543

**Comment by theashraf** [comment]
@IsaEs Use a `style` prop to control the canvas element's size on the DOM. This method allows the dotLottie React to automatically adjust the drawing surface size, ensuring the animation's quality remains consistent.

```jsx
<DotLottieReact
  style={{ width: '600px', height: '400px' }}
  src={myLottie}
  autoplay
  loop
/>
```
