### ISSUE TITLE
adobe lottie json

### ISSUE THREAD

**Issue by perfectwebtech** [LottieFiles/dotlottie-web#138]
hello

adobe after effect movin and lottie json file can work here ?

as some image and text level dynamic template possible and convert to video ? 

int his script possible or anyone can help us how to possible make dynamic tempalte so based on user we can process to mp4 

currently in adobe we getting png with base64 raw format and other text how to modify dont know

**Comment by theashraf** [comment]
Here's a revised version focusing on grammar corrections:

> Adobe After Effects, Bodymovin, and Lottie JSON files can work here?

Yes, Lottie JSON files are compatible here.

> Is it possible to create a dynamic template with images and text and then convert it to video?

Yes, it's possible to convert Lottie animations to video. You can upload your Lottie animation to LottieFiles.com and convert it to various formats like GIF, MP4, and more. 

Also `dotlottie-web` can be used to convert a Lottie JSON  or dotLottie to a GIF. For more details on how to do this, you might find this blog post helpful: [Converting dotLottie Animations to GIFs with dotLottie Web Player](https://lottiefiles.com/blog/working-with-lottie-animations/converting-dotlottie-animations-to-gifs-with-dotlottie-web-player/). 

Converting a Lottie to an MP4 video format programmatically would be quite similar to the approach discussed that blog post, and using a tool like `ffmpeg` is recommended. This involves encoding the animation's frames, previously exported as images, into a video file.

> Currently, in Adobe, we are getting PNG with base64 raw format and other text. How to modify, I don't know.

For editing PNG images and text in your Lottie animation, consider using editor.lottiefiles.com. It's user-friendly and convenient for making such modifications.

**Comment by theashraf** [comment]
> adobe after effect movin and lottie json file can work here ?

Yes, Lottie JSON files are compatible here.

> as some image and text level dynamic template possible and convert to video ?
> int his script possible or anyone can help us how to possible make dynamic tempalte so based on user we can process to mp4

Yes, it's possible to convert Lottie animations to video. You can upload your Lottie animation to LottieFiles.com and convert it to various formats like GIF, MP4, and more. 

Also `dotlottie-web` can be used to convert a Lottie JSON  or dotLottie to a GIF. For more details on how to do this, you might find this blog post helpful: [Converting dotLottie Animations to GIFs with dotLottie Web Player](https://lottiefiles.com/blog/working-with-lottie-animations/converting-dotlottie-animations-to-gifs-with-dotlottie-web-player/). 

Converting a Lottie to an MP4 video format programmatically would be quite similar to the approach discussed that blog post, and using a tool like `ffmpeg` is recommended. This involves encoding the animation's frames, previously exported as images, into a video file.

> currently in adobe we getting png with base64 raw format and other text how to modify dont know

For editing PNG images and text in your Lottie animation, consider using editor.lottiefiles.com. It's user-friendly and convenient for making such modifications.

**Comment by theashraf** [comment]
@perfectwebtech closing this issue, feel free to raise any questions here or on the GH Discussions, thanks
