### ISSUE TITLE
Use DotLottie Web with Nuxt 2

### ISSUE THREAD

**Issue by skiddyvn** [LottieFiles/dotlottie-web#140]
## Overview

- I want to use dotLottie web player on a Nuxt 2 project. But it seems there is an issue with the file loader. I haven't found a solution for this case yet (Currently only topic related to Nuxt 3 is opened)
`Module parse failed: Unexpected token.
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.`
![image](https://github.com/LottieFiles/dotlottie-web/assets/45237572/4e19602b-18bf-4fb0-ab74-820686597f44)

- My reproduce repo:
[Codesandbox](https://codesandbox.io/p/devbox/83c2k3?migrateFrom=k62m5c&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clto4ndc300062866limmloe4%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clto4ndc300022866zlxhsjsg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clto4ndc300042866fqeb2aun%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clto4ndc300052866npcwdkue%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clto4ndc300022866zlxhsjsg%2522%253A%257B%2522id%2522%253A%2522clto4ndc300022866zlxhsjsg%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clto4ndc300052866npcwdkue%2522%253A%257B%2522id%2522%253A%2522clto4ndc300052866npcwdkue%2522%252C%2522activeTabId%2522%253A%2522clto4poar00d92866ifepk0v1%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clto4poar00d92866ifepk0v1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clto4ndc300042866fqeb2aun%2522%253A%257B%2522id%2522%253A%2522clto4ndc300042866fqeb2aun%2522%252C%2522activeTabId%2522%253A%2522clto59iaf01ox2866y459ixol%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clto4ndc300032866fifp3qgx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clto4nduj001adhf82i9t4jgw%2522%257D%252C%257B%2522id%2522%253A%2522clto4tl6j011f28669p1zzpne%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clto4tlch0035dhf89rorctjb%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clto59iaf01ox2866y459ixol%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

- I used node v20.11.1 and nuxt 2.15.7.

So I would like to know if dotLottie currently support Nuxt 2. Thank you!

**Comment by afsalz** [comment]
Hey @skiddyvn, I believe the issue with @lottiefiles/dotlottie-web stems from its use of ES Module syntax, as indicated by "type": "module" in its package.json. This leads Webpack in Nuxt v2 to load the ES Module version of the library instead of the CommonJS version, which might not be fully compatible without additional configuration.

To work around this, you can instruct Nuxt to explicitly transpile the library, ensuring it's converted into a format that Webpack can handle seamlessly. You can achieve this by adding @lottiefiles/dotlottie-web to the transpile list in your nuxt.config.js like so:

```
export default {
  ssr: false,
  build: {
    transpile: ['@lottiefiles/dotlottie-web'], // Ensure this line is added
  },
};
```
I've forked your CodeSandbox to implement this fix, and you can check out the working solution here: https://codesandbox.io/p/devbox/nuxt-dotlottie-forked-wjwy8p.

Let me know if this resolves the issue or if there’s anything else I can help with!

**Comment by skiddyvn** [comment]
@afsalz Thank you, it works well now
