### ISSUE TITLE
Different rendering result compared to lottie-web

### ISSUE THREAD

**Issue by ebeloded** [LottieFiles/dotlottie-web#143]
## Overview

When rendering a simple animation from the same JSON file, the result is different when using dotlottie-web compared to lottie-web. The dotlottie-web rendering produces unexpected opaque center within the rocket:

![2024-03-15 at 12 19 38](https://github.com/LottieFiles/dotlottie-web/assets/5859177/66e0c63a-aa42-46de-a274-0509c7363e72)

In the above example, lottie-web uses canvas renderer for fair comparison. Both use the same JSON file as a source. I tried converting JSON to dotlottie format, but it didn't change the result.

## Reproduction

I created minimal reproduction that can be observed here: https://stackblitz.com/edit/vitejs-vite-2pieau?file=src%2FApp.svelte

**Comment by theashraf** [comment]
Thanks @ebeloded for bringing this issue, it appears this might be related to `ThorVG` (the underlying rendering engine used by dotlottie-web). 

@hermet Can you help have a look at this issue ? This version of `dotlottie-web` is using `ThorVG@v0.12.7`

**Comment by hermet** [comment]
@ebeloded @theashraf hello, this issue will be fixed in thorvg 0.12.10, thanks for reporting!

**Comment by ebeloded** [comment]
Great! Thank you!
