### ISSUE TITLE
Incorrect Path Usage in DotLottieReact Component

### ISSUE THREAD

**Issue by CatCodeDanix** [LottieFiles/dotlottie-web#151]
**Description:**
In the current implementation of the DotLottieReact component within the @lottiefiles/dotlottie-react library, there seems to be an inconsistency in the way paths are handled, causing confusion and potential errors for users.

**Problem:**
When attempting to utilize the DotLottieReact component in a Vite + React project, users are encountering issues related to incorrect path usage. Specifically, the component fails to render the Lottie animation when the src prop is assigned a relative path ("./animation.lottie"), resulting in a broken animation.

**Failing Code:**
```javascript
import { DotLottieReact } from "@lottiefiles/dotlottie-react";

function App() {
  return <DotLottieReact src="./animation.lottie" loop autoplay />;
}

export default App;
```

**Expected Behavior:**
The DotLottieReact component should successfully render the Lottie animation when provided with a relative path to the animation file.

**Working Code:**
```javascript
import { DotLottieReact } from "@lottiefiles/dotlottie-react";

function App() {
  return <DotLottieReact src="../src/animation.lottie" loop autoplay />;
}

export default App;
```

**Explanation:**
Upon investigation, it appears that the DotLottieReact component requires a precise path to the Lottie animation file in order to render it correctly. However, the documentation or error messages do not provide clear guidance on this requirement, leading to confusion among users.

**Proposed Solution:**
Documentation Improvement: Enhance the documentation of the @lottiefiles/dotlottie-react library to explicitly specify the correct path usage for the src prop, providing examples and explanations to guide users effectively.

Error Handling: Implement more informative error messages within the library that notify users when an incorrect path is provided to the DotLottieReact component, helping them identify and resolve issues more efficiently.

**Additional Information:**
Library Version: 0.5.1
Environment: Vite + React + JS (in Visual Studio Code)
Operating System: Windows 10

This issue seeks to improve the usability and reliability of the @lottiefiles/dotlottie-react library, ensuring a smoother experience for developers integrating Lottie animations into their Vite + React projects. Any assistance or clarification on this matter would be greatly appreciated. Thank you.

**Comment by theashraf** [comment]
@CatCodeDanix The `DotLottieReact` `src` prop expects an absolute or relative URL, not a file path. If you're using Vite, you can import your assets by their path using the URL loader in the following way: 

```javascript
import animationUrl from "./src/animation.lottie?url";
```

Then, you can pass this down to the `DotLottieReact` component's `src` prop:

```javascript
import React from 'react';
import { DotLottieReact } from "@lottiefiles/dotlottie-react";
import animationUrl from "./src/animation.lottie?url"; // Import the animation as a URL

function App() {
  return (
    <DotLottieReact src={animationUrl} loop autoplay />
  );
}

export default App;
```

**Comment by CatCodeDanix** [comment]
Thank you for the guidance! The solution you provided works perfectly. However, I think it would have been beneficial if the DotLottieReact component could handle file paths directly. Nonetheless, I appreciate your assistance in resolving the issue.
