### ISSUE TITLE
RuntimeError: table index is out of bounds

### ISSUE THREAD

**Issue by wottpal** [LottieFiles/dotlottie-web#170]
Get `RuntimeError: table index is out of bounds` when trying to embed the attached .lottie (replace `.zip` with `.lottie`) file via `dotlottie-react`.

**File:** [lush3n7n.zip](https://github.com/LottieFiles/dotlottie-web/files/14919881/lush3n7n.zip)

![CleanShot 2024-04-09 at 16 27 43@2x](https://github.com/LottieFiles/dotlottie-web/assets/3930150/bdc3d7fd-bd25-4710-8f83-93026648464b)

**Comment by theashraf** [comment]
@wottpal, thank you for reporting this issue. I will look into it and get back to you. 

I've tested the Lottie JSON, and it works fine on our renderer, so the issue likely lies within the [dotlottie-rs](github.com/LottieFiles/dotlottie-rs)

**Temporarily** for now, you might consider uploading your .zip/.lottie asset to lottiefiles.com to generate a Lottie JSON asset link. This way, you can load your animation in dotlottie-react.

**Comment by theashraf** [comment]
@wottpal this issue has been fixed in dotlottie-web@0.20.0
