### ISSUE TITLE
AE loopOut() does not work

### ISSUE THREAD

**Issue by Rapsssito** [LottieFiles/dotlottie-web#175]
## Overview

I am testing an animation moving from `@dotlottie/player-component` to `@lottiefiles/dotlottie-web`. [Animation link](https://adelantevalladolid.es/wp-content/uploads/2023/11/hero-web.lottie).

With `@dotlottie/player-component` it works flawlessly. However, when running the animation with `@lottiefiles/dotlottie-web`, some parts do not work. In my case, the "bike" animation at the end (which was created using the `loopOut()` command in AE), does not loop.

**Comment by theashraf** [comment]
@Rapsssito The loopOut expression is not yet supported by our Lottie renderer (ThorVG). For more information, please refer to [this issue](https://github.com/thorvg/thorvg/issues/1640).

@hermet Are there any plans to add `loopOut` support soon?

**Comment by hermet** [comment]
Hi, we are working on adding support for expressions (https://github.com/thorvg/thorvg/issues/1640) and will be including the `loopOut()` function in the specification. The expected date for this feature release is in the upcoming minor release, v0.14, scheduled for June.

**Comment by theashraf** [comment]
@hermet, has loopOut() been implemented in thorvg@0.13.4?

**Comment by hermet** [comment]
In expressions, yes

**Comment by theashraf** [comment]
@Rapsssito This has been resolved in latest dotlottie-web@0.22.0
