### ISSUE TITLE
Animation lags (skips frames) when moving to the background and back to the foreground

### ISSUE THREAD

**Issue by Rapsssito** [LottieFiles/dotlottie-web#176]
## Overview

I've noticed that when going to another tab or another window (for a while), the animation starts to lag and skip frames (I'm using Mozilla Firefox). The lag (skipped frames) continues even when the animation loops.

## Labels

- [ ] Add the `Type: Bug` label to this issue.

**Comment by theashraf** [comment]
@Rapsssito can you share the player usage code in this case ?

**Comment by Rapsssito** [comment]
@theashraf, the animation I am using is the same that I provided in #175 (which is also the same I was using when I discovered #174).

**Comment by theashraf** [comment]
@Rapsssito, I'm unable to replicate this issue, but I can suggest a few enhancements that might help in this case.

You may want to consider disabling frame interpolation. Here's how you can modify your code:

```js
import { DotLottie } from 'https://cdn.jsdelivr.net/npm/@lottiefiles/dotlottie-web/+esm';
const canvas = document.getElementById('dotlottie-canvas');
const player = new DotLottie({
    autoplay: true,
    loop: true,
    canvas,
    src: canvas.getAttribute('data-src'),
    // Disable frame interpolation for better performance, this will make the player not render the in-between frames
    useFrameInterpolation: false,
});
```

It would also be helpful if you could run performance profiling and download the profiling data. This would allow me to better investigate this issue.

**Comment by Rapsssito** [comment]
@theashraf, thanks for the answer. However, using the changes you proposed in #174, it doesn't seem like the issue is still occurring. I will close this issue for now.
