### ISSUE TITLE
Trim paths speed do not match original clip

### ISSUE THREAD

**Issue by Rapsssito** [LottieFiles/dotlottie-web#178]
## Overview

Sorry for opening these many issues. We are moving from `@dotlottie/player-component` to `@lottiefiles/dotlottie-web` and we want to make sure everything works as expected. We are primarily working with this [animation](https://adelantevalladolid.es/wp-content/uploads/2023/11/hero-web.lottie).

With `@dotlottie/player-component` it works flawlessly. However, when running the animation with `@lottiefiles/dotlottie-web`, some paths (trimming) go much faster than expected (only some of them). In the case of our animation, the windows of some houses are drawn too quickly. Example (I highlighted some of the mismatches in red):

https://github.com/LottieFiles/dotlottie-web/assets/44206249/e37df481-6b07-495d-acb0-fcdd0a276f98

You can check the same animation running with each package in:
- `@lottiefiles/dotlottie-web`: https://adelantevalladolid.es/test-lottiefiles/ (password: test)
- `@dotlottie/player-component`: https://adelantevalladolid.es/

**Comment by theashraf** [comment]
@mgrudzinska This should have been fixed in the latest dotlottie-web@0.21.0
