### ISSUE TITLE
TypeScript: getDotLottieInstance should be defined (vue3)

### ISSUE THREAD

**Issue by emmanuelgeoffray** [LottieFiles/dotlottie-web#187]
## Overview

![image](https://github.com/LottieFiles/dotlottie-web/assets/808090/a0b7ee0a-d0db-4074-b7ef-ff8c8ccb22f0)

The [doc for the vue package mentions a getDotLottieInstance function](https://github.com/LottieFiles/dotlottie-web/tree/main/packages/vue#listening-to-events) but it is not in the component typing.

getDotLottieInstance is not defined, triggering TS issues and losing type.

I think that we should use `defineExpose` at this [line](https://github.com/LottieFiles/dotlottie-web/blob/main/packages/vue/src/dotlottie.ts#L150)

as explained in the Vue docs [here](https://vuejs.org/guide/typescript/composition-api#typing-component-template-refs)

## Consuming repo

dotlottie-vue

## Labels

- [x] Add the `Type: Bug` label to this issue.

**Comment by theashraf** [comment]
@afsalz any updates on this ?

**Comment by afsalz** [comment]
Hi @emmanuelgeoffray ,

We are using the `defineComponent` function to define our Vue component. It appears that defineExpose primarily works with .vue files.

In our current setup, we receive the expose function as a second argument in the setup function, as shown below:

js```
import { defineComponent } from 'vue';

export default defineComponent({
  setup(props, { expose }) {
    expose({
      someMethod() {
        // ...
      }
    });
  }
});
```
We tried using `defineExpose`, but it doesn't seem to have any effect in this context.

If you have a solution, we would greatly appreciate your contribution.

@theashraf  , we are actively working on a solution for this.

Thank you!

**Comment by emmanuelgeoffray** [comment]
hey @afsalz 
thank you for your work on this bug.
I'm sorry but no, I don't know the solution :)
Maybe you will find it in other projects that provide components for both vue and react, like Tiptap or Moveable.

**Comment by afsalz** [comment]
Hey guys, 

I have created a PR introducing type `DotLottieVueInstance` which solves this issue.


https://github.com/LottieFiles/dotlottie-web/assets/128362946/ba992850-b6d6-44d4-81de-f54975300ea1
