### ISSUE TITLE
Live examples (and probably this package) isn't working

### ISSUE THREAD

**Issue by harishash** [LottieFiles/dotlottie-web#189]
## Overview
Both Live examples given on the homepage aren't working.
- [Getting Started](https://codepen.io/lottiefiles/pen/vYPJpBN)
- [Custom Playback Controls](https://codepen.io/lottiefiles/pen/WNmEdxd)
...

## Consuming repo
N/A
> What repo were you working in when this issue occurred?
I set up a simple nextjs project, added the library and followed the instructions given in the docs but the lottie wasn't appearing. I thought maybe I'm doing something wring until I checked the codepen examples which are displaying a similar behaviour.
...

## Labels
- `Type: Bug`

**Comment by theashraf** [comment]
Thanks to @harishash for pointing out this issue. The importmap was missing. I've fixed the examples, and they should now work
