### ISSUE TITLE
Rounded corners missing but work in @dotlottie/player-component

### ISSUE THREAD

**Issue by joelisfar** [LottieFiles/dotlottie-web#190]
## Overview
An animation I’m using has an issue where many of its rounded corners are missing when it’s played in `dotlottie-web` players but not in `@dotlottie/player-component`.

Example without defect: https://codepen.io/jifarris/pen/JjqjNGO

Example with defect: https://codepen.io/jifarris/pen/gOJOWbZ

In this video I switch between the two to show the differences:
https://github.com/LottieFiles/dotlottie-web/assets/2447045/694f2a5e-0f6a-4edf-9cd6-8f9dbc521b52

I’d love to know if this is something that can be fixed, either in dotlottie-web or in the after effects file, if needed.

<img width="673" alt="Screenshot 2024-05-09 at 2 27 51 PM" src="https://github.com/LottieFiles/dotlottie-web/assets/2447045/06c27b27-9fbd-4e5c-a089-c0b30efb3395">

---

## Consuming repo

> What repo were you working in when this issue occurred?

https://github.com/LottieFiles/dotlottie-web

## Labels

- [ ] Add the `Type: Bug` label to this issue.

**Comment by hermet** [comment]
cc @mgrudzinska

**Comment by hermet** [comment]
Hello, the enhancement will be applied in ThorVG v0.13.4 Thanks.

**Comment by theashraf** [comment]
@joelisfar This has been resolved in latest dotlottie-web@0.22.0
