### ISSUE TITLE
Add segment duration getter

### ISSUE THREAD

**Issue by rismirnov** [LottieFiles/dotlottie-web#194]
## Overview

I suggest adding a getter to get the duration of a given segment [startFrame, endFrame].

```js
const player = new DotLottie({ segment: [0, 100], /* other params */ })
const frameRate = player.totalFrames / player.duration;
const segmentDuration = 1000 * (player.segment[1] - player.segment[0] + 1) / frameRate;
```

## Type

- [ ] New feature

## Motivation

I needed to determine how much time remained before the segment would finish playing after some time

## Labels

- [ ] Add the `Type: Feature Request` label to this issue.

**Comment by theashraf** [comment]
Thanks @rismirnov  
I think this is a good addition. Just one note from my side: to minimize the impact on the bundle size, we can add this as a utility function that we export from our dotlottie-web package for optional use. Adding it directly to the DotLottie class would unnecessarily increase the bundle size, as this is not a very common use case.

**Comment by theashraf** [comment]
@rismirnov has been added in `@lottiefiles/dotlottie-web@0.23.0`
