### ISSUE TITLE
Set speed

### ISSUE THREAD

**Issue by rismirnov** [LottieFiles/dotlottie-web#195]
## Overview

If you first reduce the animation speed `setSpeed(0.1)`, and then (after some time) increase `setSpeed(1)`, then the animation jumps forward (as if the animation speed was always equal to "1").
You can observe this behavior in any linear animation, like
https://lottiefiles.com/animations/progress-bar-fast-4mRIN4LXSY

_This code will break the animation_

```js
/* BAD CODE */
player.setSpeed(0.1)
setTimeout(() => {
    player.setSpeed(1)
}, 1000)
```
Corrects the behavior by calling pause() before setting the new speed.
```js
player.setSpeed(0.1)
setTimeout(() => {
    player.pause()
    player.setSpeed(1)
    player.play()
}, 1000)
```
## Consuming repo

dotlottie-web

## Labels

- [ ] Add the `Type: Bug` label to this issue.

**Comment by theashraf** [comment]
@rismirnov this issue is resolved in [@lottiefiles/dotlottie-web@0.23.0](https://github.com/LottieFiles/dotlottie-web/releases/tag/%40lottiefiles%2Fdotlottie-web%400.23.0)
