### ISSUE TITLE
Lottie matte rendering artifacts with lines

### ISSUE THREAD

**Issue by andrewvarga** [LottieFiles/dotlottie-web#214]
## Overview

if I have a rectangle and apply another one to it as a matter layer it works.
However if I have a line (2 point bezier path) with a large stroke, which also looks like a rectangle and apply a matte to that, I get some strange artifacts in the lottie web player, the bodymovin player or in lottiefiles Playground.

This is what it should look like (the bottom shape is a line, both are masked by a rectangle):
<img width="357" alt="330696305-3b958ea6-1ee6-41cf-83cf-4a57b37794be" src="https://github.com/LottieFiles/dotlottie-web/assets/911440/27b8ba63-4bc7-4aca-8aa9-fdf00a53bac9">

This is what it actually looks like (ignore the transparent background, note the weird shape of the bottom shape):
<img width="209" alt="330696378-d6ee3c4d-b8a5-4d9c-8a36-ea4ed2de69ee" src="https://github.com/LottieFiles/dotlottie-web/assets/911440/86134b58-b6ba-4254-897f-370816d069f0">

To me this looks like a bug in the Lottie player / renderer. Can someone confirm and advise about a fix or workaround?
Thank you!

Here is the lottie file to test:
[matte_bugs.lottie.json](https://github.com/LottieFiles/dotlottie-web/files/15443593/matte_bugs.lottie.json)

## Labels

- [x] Add the `Type: Bug` label to this issue.

**Comment by hermet** [comment]
@andrewvarga Hello, we checked this, and it is not a dotLottie issue but a Lottie-web problem (https://github.com/LottieFiles/lottie-player). So, you shouldn't have any problems with dotLottie-web. Thanks.

**Comment by theashraf** [comment]
> > @andrewvarga Hello, we checked this, and it is not a dotLottie issue but a lottie-web problem (https://github.com/LottieFiles/lottie-player). So, you shouldn't have any problems with dotLottie-web. Thanks.
> 
> Thank you! I think we should we switch to this dotlottie player from lottie-web, it seems it's more mature - do you agree? Do you foresee any possible downsides for this? The way I see dotlottie player also supports simple "json" lottie files, besides the binary dotlottie format so that shouldn't be an issue.

One significant advantage of the dotLottie player over lottie-web and lottie-android is its consistent rendering. This consistency is achieved by using the same rendering engine ([ThorVG](https://github.com/thorvg/thorvg)) across all dotLottie players, with a single core codebase ([dotlottie-rs](https://github.com/LottieFiles/dotlottie-rs)) that is cross-compiled to Kotlin, Swift, and WASM for web use. While describing it as more mature can be subjective and depends on the specific Lottie animation features in use, the dotLottie player does support some features that lottie-android does not, and vice versa.

In my opinion, the primary benefit is the ability to play .lottie format files, which are smaller in size compared to the standard lottie json format.
