### ISSUE TITLE
Matte parent "tp" support

### ISSUE THREAD

**Issue by andrewvarga** [LottieFiles/dotlottie-web#219]
## Overview

This is partly a bug report, partly just a question.
There is this "tp" property on layers which is said to be working like this:
"Index of the layer used as matte, if omitted assume the layer above the current one"

This seems to work well for the lottie web player, but the way I see it's not working on android.
Is there a way to know if that's a bug which can be reported somewhere, or just a missing feature and it is not expected to be supported in the future?

## Consuming repo

Create 3 shape layers
Make the bottom one use "tp" pointing to the first layer's index along with "tt" with a valid matte mode
Add "td": 1 to the first layer so it's a matte target

This works on web but not on the android lottiefiles player. There I can only make it work by using the layer above as a matte target without specifying "tp".

> What repo were you working in when this issue occurred?

...

## Labels

- [x] Add the `Type: Bug` label to this issue.

**Comment by theashraf** [comment]
@andrewvarga This is an unsupported feature in the dotlottie-web lottie renderer, which uses thorvg. I will update you once it's fixed. Thanks!

**Comment by andrewvarga** [comment]
> @andrewvarga This is an unsupported feature in the dotlottie-web lottie renderer, which uses thorvg. I will update you once it's fixed. Thanks!

Thanks for the reply!
To confirm, what does this mean for android/mobile, is it expected to be working there eventually or not really?

**Comment by hermet** [comment]
+ @kudanai

**Comment by kudanai** [comment]
If you mean [airbnb/lottie-android](https://github.com/airbnb/lottie-android) then I'm not sure if it's planned or not. I'll have a look into it and see if it's feasible.

For dotlottie-android, it would be fixed alongside dotlottie-web as it uses a shared codebase.

**Comment by andrewvarga** [comment]
> If you mean [airbnb/lottie-android](https://github.com/airbnb/lottie-android) then I'm not sure if it's planned or not. I'll have a look into it and see if it's feasible.
> 
> For dotlottie-android, it would be fixed alongside dotlottie-web as it uses a shared codebase.

I'm not familiar with these formats, which one is being used by the Lottiefiles android app?
Is there a reason someone would prefer airbnb/lottie-android?

**Comment by kudanai** [comment]
They're two flavors of players. The Airbnb player is the older mature player. 

Our dotlottie-xx players are a new breed of players based on the ThorVG graphics engine.

They both use Lottie (standard json based format), while dotlottie-xx also supports additional extensions (i.e. dotLottie). You can read more about it at developers.lottiefiles.com

**Comment by andrewvarga** [comment]
> They're two flavors of players. The Airbnb player is the older mature player.
> 
> Our dotlottie-xx players are a new breed of players based on the ThorVG graphics engine.
> 
> They both use Lottie (standard json based format), while dotlottie-xx also supports additional extensions (i.e. dotLottie). You can read more about it at developers.lottiefiles.com

thanks, makes sense. So to confirm this android application is using the dotlottie-xx player?
https://play.google.com/store/apps/details?id=com.lottiefiles.LottiePreview&hl=en&gl=US

Meaning "tp" support can be expected there?

**Comment by kudanai** [comment]
At the moment no, that app uses lottie-android
we're currently working on migrating it over to the new player

**Comment by hermet** [comment]
@andrewvarga @theashraf the fix will be applied in thorvg v0.13.6 by @mgrudzinska

**Comment by andrewvarga** [comment]
> @andrewvarga @theashraf the fix will be applied in thorvg v0.13.6 by @mgrudzinska

Great thank you! 
Just to confirm, that means that I'll be able to use "tp" to reference the matte layer without needing to place it directly above the layer that gets the matte applied?

And eventually that will propagate to LottieFile website and the android player.
What is your typical release schedule?

**Comment by hermet** [comment]
@andrewvarga yes. the layer order doesn't matter.
@theashraf thorvg v0.13.6 will be released on this Friday.

Thanks.

**Comment by theashraf** [comment]
Thanks, @hermet!! 

@andrewvarga, the updated versions of [dotlottie-android](https://github.com/LottieFiles/dotlottie-android) and dotlottie-web will be released early next week.

**Comment by theashraf** [comment]
@andrewvarga thorvg v0.13.6 has been updated in `@lottiefiles/dotlottie-web@0.23.0`, [dotlottie-android](https://github.com/LottieFiles/dotlottie-android) will be updated maybe early next week

**Comment by andrewvarga** [comment]
> @andrewvarga thorvg v0.13.6 has been updated in `@lottiefiles/dotlottie-web@0.23.0`, [dotlottie-android](https://github.com/LottieFiles/dotlottie-android) will be updated maybe early next week

Great, thank you!
So this playground I see here is using the latest thorvg based dotlottie player?
https://lottiefiles.github.io/lottie-docs/playground/json_editor/

Or is there a similar playground I can try that player?

**Comment by theashraf** [comment]
> > @andrewvarga thorvg v0.13.6 has been updated in `@lottiefiles/dotlottie-web@0.23.0`, [dotlottie-android](https://github.com/LottieFiles/dotlottie-android) will be updated maybe early next week
> 
> Great, thank you! So this playground I see here is using the latest thorvg based dotlottie player? https://lottiefiles.github.io/lottie-docs/playground/json_editor/
> 
> Or is there a similar playground I can try that player?

@andrewvarga you can test it out on https://lottiefiles.github.io/dotlottie-web/
