### ISSUE TITLE
`lottie.json` works with `svelte-lottie-player` but not `dotlottie`

### ISSUE THREAD

**Issue by baseplate-admin** [LottieFiles/dotlottie-web#221]
## Overview
the following json file works with[ `svelte-lottie-player` ](https://www.npmjs.com/package/@lottiefiles/svelte-lottie-player) [notification.json](https://github.com/LottieFiles/dotlottie-web/files/15493743/notification.json) but it freezes the entire browser window when i use it from [`dotlottie`](https://www.npmjs.com/package/@lottiefiles/dotlottie-svelte).

Here is the [profile of my firefox](https://profiler.firefox.com/public/6vsn29ss09pjmd4wavcmrhtp19f5ntg8rf60ez0/calltree/?globalTrackOrder=ij0wh&hiddenGlobalTracks=1wf&hiddenLocalTracksByPid=14112-0w4%7E2856-0%7E10092-0%7E24556-0%7E16680-0%7E18956-0%7E20664-0%7E24456-0%7E10152-0%7E4684-0%7E3104-0%7E25236-0%7E14080-0%7E2896-01%7E18928-01%7E23440-01%7E14016-0w3%7E2088-0w3&implementation=js&thread=s&v=10)

it recursively calls to `jsdelivr` for some reason

## Consuming repo

> What repo were you working in when this issue occurred?

https://github.com/baseplate-admin/coreproject-v4-ui/tree/fix/dotlottie

https://github.com/baseplate-admin/coreproject-v4-ui/blob/829798be2ea9111a091a657381edf1ac7e264a61/src/routes/anime/%2Blayout.svelte#L17

https://github.com/baseplate-admin/coreproject-v4-ui/blob/829798be2ea9111a091a657381edf1ac7e264a61/src/routes/anime/%2Blayout.svelte#L169

## Labels

- [x] Add the `Type: Bug` label to this issue.

**Comment by baseplate-admin** [comment]
https://github.com/LottieFiles/dotlottie-web/blob/e9f9a6e02ab3dc1cb161446b5876ccdf072be22d/packages/web/src/core/dotlottie-wasm-loader.ts#L16

Here is the suspected line i think

**Comment by theashraf** [comment]
Thanks @baseplate-admin, will have a look and let you know

**Comment by baseplate-admin** [comment]
Also one more issue i faced.

LottiePlayer supports **JS Object** as input, `dotlottie` doesn't support it. Should this be opened in another issue?

**Comment by theashraf** [comment]
> Thanks a lot for taking a look into this.
> 
> Also one more issue i faced. LottiePlayer supports **JS Object** as input, `dotlottie` doesn't support it. Should this be opened in another issue?

sure, feel free to open another issue

**Comment by theashraf** [comment]
@baseplate-admin This issue is fixed in the latest dotlottie-svelte v0.3.4 release. You can verify if it's working as expected in the dotlottie-viewer at https://lottiefiles.github.io/dotlottie-web/. Thanks
