### ISSUE TITLE
The dotlottie-wc web component does not display correctly when the height is set to auto. It requires a min-height or explicit height value to render properly.

### ISSUE THREAD

**Issue by vsarangan** [LottieFiles/dotlottie-web#230]
**Steps to Reproduce:**

Include the dotlottie-wc component in your HTML.
Set the height of the component to auto (e.g., via CSS).
Observe that the component does not render or display as expected.

**Expected Behavior:**
The dotlottie-wc component should automatically adjust its height based on the content and display correctly when the height is set to auto.

**Actual Behavior:**
The dotlottie-wc component does not render or display correctly when the height is set to auto. It only displays correctly when a min-height or explicit height value is provided.

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>dotlottie-wc Test</title>
    <script type="module" src="https://unpkg.com/@lottiefiles/dotlottie-wc@latest/dist/dotlottie-wc.js"></script>
  <style>
    .lottie-container {
      width: 100%;
      height: auto; /* The problematic setting */
    }
  </style>
</head>
<body>
  <div class="lottie-container">
       <dotlottie-wc src="https://lottie.host/4db68bbd-31f6-4cd8-84eb-189de081159a/IGmMCqhzpt.lottie" autoplay loop></dotlottie-wc>

  </div>
</body>
</html>
```

**Comment by theashraf** [comment]
Thanks, @vsarangan. I'll take a look and let you know

**Comment by theashraf** [comment]
@vsarangan It looks OK to me. The canvas width or height will follow its parent container's width and height, and the player will determine the drawing surface area based on the width and height of the canvas in a way that maintains the aspect ratio. To me, this seems to be the correct aspect ratio of the animation. 

Can you provide a CodePen with the reproducible issue you're referring to ? Thanks.

<img width="300" alt="image" src="https://github.com/LottieFiles/dotlottie-web/assets/39750790/2c23808e-15b8-49c0-a9f5-12fa50517a77">

**Comment by vsarangan** [comment]
> @vsarangan It looks OK to me. The canvas width or height will follow its parent container's width and height, and the player will determine the drawing surface area based on the width and height of the canvas in a way that maintains the aspect ratio. To me, this seems to be the correct aspect ratio of the animation.
> 
> Can you provide a CodePen with the reproducible issue you're referring to ? Thanks.
> 
> <img alt="image" width="300" src="https://private-user-images.githubusercontent.com/39750790/336336129-2c23808e-15b8-49c0-a9f5-12fa50517a77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTExODIsIm5iZiI6MTcxNzQ5MDg4MiwicGF0aCI6Ii8zOTc1MDc5MC8zMzYzMzYxMjktMmMyMzgwOGUtMTViOC00OWMwLWE5ZjUtMTJmYTUwNTE3YTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA4NDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNjVlNDFlOTkwMTY3NjI4MzM5YzA0OTZjMTk5Yzk1MTUwYzg3MjJlYTk2Zjc2MmU2ZGEwMTU5NGM2YzIwYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TpCIgGdLDM65NOfxplmEk2RsPbt3pZYsVkH-bMlFzFU">

**Comment by vsarangan** [comment]
> > @vsarangan It looks OK to me. The canvas width or height will follow its parent container's width and height, and the player will determine the drawing surface area based on the width and height of the canvas in a way that maintains the aspect ratio. To me, this seems to be the correct aspect ratio of the animation.
> > Can you provide a CodePen with the reproducible issue you're referring to ? Thanks.
> > <img alt="image" width="300" src="https://private-user-images.githubusercontent.com/39750790/336336129-2c23808e-15b8-49c0-a9f5-12fa50517a77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTExODIsIm5iZiI6MTcxNzQ5MDg4MiwicGF0aCI6Ii8zOTc1MDc5MC8zMzYzMzYxMjktMmMyMzgwOGUtMTViOC00OWMwLWE5ZjUtMTJmYTUwNTE3YTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA4NDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNjVlNDFlOTkwMTY3NjI4MzM5YzA0OTZjMTk5Yzk1MTUwYzg3MjJlYTk2Zjc2MmU2ZGEwMTU5NGM2YzIwYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TpCIgGdLDM65NOfxplmEk2RsPbt3pZYsVkH-bMlFzFU">

**Comment by vsarangan** [comment]
Hi @theashraf, The dotlottie-wc component works as expected when the parent container has explicit height and width values. However, if the parent container's height is set to auto and adjusts dynamically based on its content, the component is not rendered. please refer the above code

**Comment by theashraf** [comment]
> Hi @theashraf, The dotlottie-wc component works as expected when the parent container has explicit height and width values. However, if the parent container's height is set to auto and adjusts dynamically based on its content, the component is not rendered. please refer the above code

Am i missing something in the provided code ? 
https://codesandbox.io/p/sandbox/dotlottie-wc-test-lctpdk?file=%2Findex.html%3A5%2C7
<img width="1511" alt="image" src="https://github.com/LottieFiles/dotlottie-web/assets/39750790/4035aaef-5fa0-43b4-b396-142e6c770829">

**Comment by vsarangan** [comment]
Hi @theashraf , Thanks for your response. I have provided the sample codesandbox, please use it for reference
[codesanbox](https://codesandbox.io/p/sandbox/dotlottie-wc-test-forked-p7pzz2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx1e3fpk00073j6jkya7u77y%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx1e3fpj00033j6j1w7vrfnh%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx1e3fpj00043j6jw8aks7j8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx1e3fpj00063j6jpkj603sg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx1e3fpj00033j6j1w7vrfnh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx1e3fpj00023j6jyz9ifjj4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A12%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A12%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clx1e3fpj00033j6j1w7vrfnh%2522%252C%2522activeTabId%2522%253A%2522clx1e3fpj00023j6jyz9ifjj4%2522%257D%252C%2522clx1e3fpj00063j6jpkj603sg%2522%253A%257B%2522id%2522%253A%2522clx1e3fpj00063j6jpkj603sg%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx1e3fpj00053j6ju8z64gqa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clx1e3fpj00053j6ju8z64gqa%2522%257D%252C%2522clx1e3fpj00043j6jw8aks7j8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clx1e3fpj00043j6jw8aks7j8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by theashraf** [comment]
@vsarangan  one way to solve this issue is to create an independent container for the dotlottie-wc, as shown below:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>dotlottie-wc Test</title>
    <script
      type="module"
      src="https://unpkg.com/@lottiefiles/dotlottie-wc@latest/dist/dotlottie-wc.js"
    ></script>
    <style>
      .lottie-container {
        width: 100%;
        height: auto; /* The problematic setting */
        position: relative;
      }
    </style>
  </head>
  <body>
    <div class="lottie-container">
      <div style="position: absolute; width: 100%; height: 100%">
        <dotlottie-wc
          src="https://lottie.host/4db68bbd-31f6-4cd8-84eb-189de081159a/IGmMCqhzpt.lottie"
          autoplay
          loop
        ></dotlottie-wc>
      </div>
    </div>
  </body>
</html>
```

This should help address the issue.

**Comment by vsarangan** [comment]
Hi @theashraf , Thanks for your response. Unfortunately, the suggested workaround isn't working for my use case. I am trying to use dotlottie-wc as a background image.

Actual Output: The dotlottie-wc component is taking up the entire screen height instead of the specified height.

Expected Output: The dotlottie-wc component should be 200px in height.

t
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>dotlottie-wc Test</title>
    <script
      type="module"
      src="https://unpkg.com/@lottiefiles/dotlottie-wc@latest/dist/dotlottie-wc.js"
    ></script>
    <style>
      .lottie-container {
        width: 100%;
        height: auto; /* The problematic setting */
        position: relative;
      }
    </style>
  </head>
  <body>
    <div class="lottie-container">
      <div style="position: absolute; width: 100%; height: 100%">
        <dotlottie-wc
          src="https://lottie.host/4db68bbd-31f6-4cd8-84eb-189de081159a/IGmMCqhzpt.lottie"
          autoplay
          loop
        ></dotlottie-wc>
<div class="demo">
<p>some text</p>
</div>
      </div>
    </div>
  </body
  <script>
  setTimeout(() => {
            document.querySelector('.demo').style.height = '200px';
        }, 1000);
</script>
  `

**Comment by theashraf** [comment]
@vsarangan Gotcha!!

I've updated the example to achieve the expected output

https://codesandbox.io/p/sandbox/dotlottie-wc-test-forked-r4zptd

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>dotlottie-wc Test</title>
    <script
      type="module"
      src="https://unpkg.com/@lottiefiles/dotlottie-wc@latest/dist/dotlottie-wc.js"
    ></script>
    <style>
      .lottie-container {
        width: 100%;
        height: auto;
        position: relative;
      }
      dotlottie-wc {
        position: absolute;
        width: 100%;
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div class="lottie-container">
      <dotlottie-wc
        src="https://lottie.host/4db68bbd-31f6-4cd8-84eb-189de081159a/IGmMCqhzpt.lottie"
        autoplay
        loop
      ></dotlottie-wc>
      <div class="demos">
        <p>Some text</p>
      </div>
    </div>
    <script>
      setTimeout(() => {
        document.querySelector(".demos").style.height = "200px";
      }, 1000);
    </script>
  </body>
</html>
```

**Comment by vsarangan** [comment]
Hi @theashraf , Thank you for your reply. We've already implemented the suggestion mentioned above, and it's functioning well as provided earlier [codesandbox(https://codesandbox.io/p/sandbox/dotlottie-wc-test-forked-p7pzz2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx1e3fpk00073j6jkya7u77y%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx1e3fpj00033j6j1w7vrfnh%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx1e3fpj00043j6jw8aks7j8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx1e3fpj00063j6jpkj603sg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx1e3fpj00033j6j1w7vrfnh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx1e3fpj00023j6jyz9ifjj4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A12%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A12%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clx1e3fpj00033j6j1w7vrfnh%2522%252C%2522activeTabId%2522%253A%2522clx1e3fpj00023j6jyz9ifjj4%2522%257D%252C%2522clx1e3fpj00063j6jpkj603sg%2522%253A%257B%2522id%2522%253A%2522clx1e3fpj00063j6jpkj603sg%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx1e3fpj00053j6ju8z64gqa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clx1e3fpj00053j6ju8z64gqa%2522%257D%252C%2522clx1e3fpj00043j6jw8aks7j8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clx1e3fpj00043j6jw8aks7j8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) We now have a use case where we need to retrieve the height and width information of the .lottie file. Is there any available option to obtain this information?

**Comment by theashraf** [comment]
@vsarangan Glad that it works

There is no direct way at the moment to retrieve the original width and height of the animation

**Comment by vsarangan** [comment]
@theashraf , Thanks for the prompt responses. It helps a lot

**Comment by vsarangan** [comment]
Hey @theashraf, I have a question about an error I'm encountering. Here's the error message:
dotlottie-wc :
chunk-O5GMJN34.js:1 Uncaught DOMException: Failed to construct 'ImageData': The source width is zero or not a number.
Could you help me understand what might be causing this?

**Comment by theashraf** [comment]
The `animationSize` method has been added to dotlottie-web [v0.26.0](https://github.com/LottieFiles/dotlottie-web/releases/tag/%40lottiefiles%2Fdotlottie-web%400.26.0).

You can now get the Lottie animation size and update the canvas styles accordingly after the animation is loaded.

Here is a code example:

```javascript
dotLottie.addEventListener("load", () => {
  const animationSize = dotLottie.animationSize();
  
  canvas.style.width = `${animationSize.width}px`;
  canvas.style.height = `${animationSize.height}px`;
  
  dotLottie.resize(); // Must call this method after the canvas is resized so dotLottie can resize its internal frame buffer size accordingly.
});
```

I hope this CodePen achieves what you're looking for: https://codepen.io/lottiefiles/pen/xxNNGxE

**Comment by theashraf** [comment]
> Hey @theashraf, I have a question about an error I'm encountering. Here's the error message:
> dotlottie-wc :
> chunk-O5GMJN34.js:1 Uncaught DOMException: Failed to construct 'ImageData': The source width is zero or not a number.
> Could you help me understand what might be causing this?

@vsarangan Sorry, i missed this one

do you `display: none` on DotLottieReact or its parents ?
