### ISSUE TITLE
Dotlottie requests to `jsdelivr` for `wasm` when deploying with `vite`

### ISSUE THREAD

**Issue by baseplate-admin** [LottieFiles/dotlottie-web#232]
## Overview

Hi, it seems that `dotlottie-web`  is requesting to `cdn.jsdelivr.net` when i use it with my local `vite` deployment. 

This should not happen and `dotlottie-web` should use the local `wasm` file bundled with `vite`.

Here is the affecting line i think:

https://github.com/LottieFiles/dotlottie-web/blob/bb5954bff2960a34dec3f1806a0a3ba389ad4882/packages/web/src/core/dotlottie-wasm-loader.ts#L33-L53

It's actually hard to show this error without the use of a JS debugger. Here is [my profile](https://profiler.firefox.com/public/6vsn29ss09pjmd4wavcmrhtp19f5ntg8rf60ez0/calltree/?globalTrackOrder=ij0wh&hiddenGlobalTracks=1wf&hiddenLocalTracksByPid=14112-0w4%7E2856-0%7E10092-0%7E24556-0%7E16680-0%7E18956-0%7E20664-0%7E24456-0%7E10152-0%7E4684-0%7E3104-0%7E25236-0%7E14080-0%7E2896-01%7E18928-01%7E23440-01%7E14016-0w3%7E2088-0w3&implementation=js&thread=s&v=10) that shows this call.

## Consuming repo

> What repo were you working in when this issue occurred?

`dotlottie-web`

## Labels

- [x] Add the `Type: Bug` label to this issue.

**Comment by theashraf** [comment]
@baseplate-admin you can self host the wasm file, checkout this related discussion
https://github.com/LottieFiles/dotlottie-web/discussions/198

**Comment by baseplate-admin** [comment]
Hi @theashraf, thanks for quick response. But it seems the package that i am using `dotlottie-svelte` doesn't have a easy way to override this?

**Comment by baseplate-admin** [comment]
Dont you think it's better to default to self-hosting wasm?

**Comment by theashraf** [comment]
@baseplate-admin 

We can't make it the default behavior as not all bundlers include a URL loader by default, and we can't assume that they do.

Also, dotlottie-web is supposed work in the browser without any bundler. Therefore, there are two possible mechanisms for loading the WASM in this case: first, from the CDN as it is currently configured; second, by offering self-contained JavaScript bindings from [dotlottie-rs](https://github.com/LottieFiles/dotlottie-rs), which is our cross platform core player. This approach will significantly increase the JavaScript bundle size and can negatively impact the users' page scores.

We plan to ship the self-contained, non-WASM JavaScript bindings for users running the player in non-WASM-supported environments.

I am happy to hear your suggestions to improve this piece of the dotlottie-web

**Comment by baseplate-admin** [comment]
Hi @theashraf, thanks for your quick response.

> We can't make it the default behavior as not all bundlers include a URL loader by default, and we can't assume that they do.

I am sorry for this. I have no idea on this topic.

> dotlottie-web is supposed work in the browser without any bundler.

If you use the self hosted esm bundle, in theory it would be possible to self host this wasm binary yourself.

```ts
// lottie-player.ts
import './Dotlottie.wasm' ; // It should point to https://cdn.jsdelivr.net/npm/@lottiefiles/dotlottie-web@0.23.2/dist/dotlottie-player.wasm
```

That's how packages like [colorthief-wasm-web](https://github.com/zhangyuang/color-thief-wasm/) can be used from a browser (without a bundler).

**Comment by theashraf** [comment]
@baseplate-admin 

dotlottie-web is an isomorphic javascript library that works on Node and the browser, not only the modern browsers.
Also Bundlers need to know which loader to use and how to handle module resolution requests ending with `.wasm`, we can't assume that users have `.wasm` url or file loader, that's why we have provided the `setWasmUrl` to allow users to configure how they want their WASM to be loaded. 

You're right, i was referring to the Javascript only bindings, not to the self-hosted wasm 
> This doesn't make sense to me. Cause we will be loading wasm from either the bundle or the jsdelivr. Loading from a cdn shouldn't reduce the PageInsight score compared to self-hosting the wasm.

Mostly old browsers and old versions of Node, also browsers with disabled WASM runtime 
> I am curious. Is there a platform that doesn't support wasm? I was under the impression that wasm was universal for both [node](https://nodejs.org/en/learn/getting-started/nodejs-with-webassembly), [deno](https://docs.deno.com/runtime/manual/runtime/webassembly/) and [browsers](https://caniuse.com/wasm) and even other languages like [python](https://github.com/wasmerio/wasmer-python)

Related issue: https://github.com/LottieFiles/dotlottie-rs/issues/169

Happy to address your proposal or contribution!!

**Comment by theashraf** [comment]
@baseplate-admin I will close this issue for now. Feel free to reopen it if you're unable to self-host the WASM file. 
Thanks!
