### ISSUE TITLE
`dotLottieRefCallback` always gives null instance on react dev server when StrictMode is enabled

### ISSUE THREAD

**Issue by sheey11** [LottieFiles/dotlottie-web#233]
## Overview

On react 18 dev server, the infamous strict mode will automatically unmount and remount every component to "test if the component is resilient to remounting". Since `DotLottieReact` will destory the `dotLottie` instance when unmounting, the ref callback will always carry a `null` "instance".

https://github.com/LottieFiles/dotlottie-web/blob/bb5954bff2960a34dec3f1806a0a3ba389ad4882/packages/react/src/use-dotlottie.tsx#L166-L175

Live demo: https://codesandbox.io/p/devbox/relaxed-morse-l256sp?file=%2Fapp%2Fpage.tsx

A temporary way to fix this is to disable react strict mode.

## Consuming repo

> What repo were you working in when this issue occurred?

`dotlottie-react`

## Labels

- [x] Add the `Type: Bug` label to this issue.

**Comment by theashraf** [comment]
Thanks @sheey11 for reporting this, let me know if you're interested in fixing this issue. Thanks!

**Comment by theashraf** [comment]
@sheey11 fixed in [@lottiefiles/dotlottie-react@0.6.4](https://github.com/LottieFiles/dotlottie-web/releases/tag/%40lottiefiles/dotlottie-react%400.6.4)
