### ISSUE TITLE
@lottiefiles/dotlottie-react doesn't support dynamic animation loading

### ISSUE THREAD

**Issue by shrilakshmishastry** [LottieFiles/dotlottie-web#240]
## Overview
Use case: I want to dynamically change the src of animation on completion of one loop. From the given example, I tried `dotLottie?.load`, to set src, but the animation is not getting updated 🙃 
...

## Consuming repo

next js repo

...

## Labels

- [x] Add the `Type: Bug` label to this issue.

**Comment by theashraf** [comment]
hi @shrilakshmishastry, the `src` prop in `DotLottieReact` is reactive. When the `src` prop changes, `DotLottieReact` will implicitly call the `.load` method on the `DotLottie` instance. Here's a better way to switch animations using this approach:

```tsx
import React, { useState, useEffect } from 'react';
import { DotLottieReact, DotLottie, LoopEvent } from '@lottiefiles/dotlottie-react';

function App() {
  const [dotLottie, setDotLottie] = useState<DotLottie | null>(null);
  const [src, setSrc] = useState('https://lottie.host/f315768c-a29b-41fd-b5a8-a1c1dfb36cd2/CRiiNg8fqQ.lottie');

  useEffect(() => {
    function onLoop(event: LoopEvent) {
      const loopCount = event.loopCount;

      if (loopCount === 1) {
        setSrc('https://lottie.host/647eb023-6040-4b60-a275-e2546994dd7f/zDCfp5lhLe.json');
      }
    }

    dotLottie?.addEventListener('loop', onLoop);

    return () => {
      dotLottie?.removeEventListener('loop', onLoop);
    };
  }, [dotLottie]);

  return (
    <div>
      <DotLottieReact dotLottieRefCallback={setDotLottie} src={src} autoplay loop />
    </div>
  );
}

export default App;
```

**Comment by theashraf** [comment]
@shrilakshmishastry I'll close this issue. Feel free to reopen it if the problem persists.
