### ISSUE TITLE
Dotlottie web canvas dimensions

### ISSUE THREAD

**Issue by moshbopayoneer** [LottieFiles/dotlottie-web#248]
**Overview:**
I integrated the dotlottie web package and replaced the tag from `dotlottie-player` with `canvas`. Currently, everything functions similarly to `dotlottie-player`.

However, the issue lies with the dimensions of the canvas. My website hosts numerous animations, and I'm unaware of their dimensions until they load. Consequently, I did not specify the `width` and `height` attributes for the canvas tag.

As a result, the animations appear very small, defaulting to a width of 300 and a height of 150.

**How can I display them in their original size?**

**Comment by theashraf** [comment]
@moshbopayoneer, you don't need to set the width and height of the canvas drawing area manually. Just let the canvas element take 100% of its parent container using `<canvas style="width: 100%; height: 100%" />`. The dotlottie-web library will automatically adjust the canvas drawing area width and height to maintain the animation's aspect ratio and ensure high quality on all screens, considering the devicePixelRatio.

You might also want to give dotlottie-wc a try. It's a web component wrapper over dotlottie-web and can abstract some elements, especially related to sizing and the canvas. Check it out at https://www.npmjs.com/package/@lottiefiles/dotlottie-wc

Using it is as simple as this:
```
<dotlottie-wc src="https://lottie.host/4db68bbd-31f6-4cd8-84eb-189de081159a/IGmMCqhzpt.lottie" autoplay loop></dotlottie-wc>
```

**Comment by moshbopayoneer** [comment]
So the aspect ratio is the problem, is it possible the animation will have the original dimensions?

**Comment by moshbopayoneer** [comment]
Hey Ashraf,
So this is my animation https://app.lottiefiles.com/share/4c9248d5-0c41-4fe7-9da9-4bda33268a8a
(dimensions 334 × 466 PX)

and this is how it looks like on my website (wrong dimensions 346 x 572.95) using @lottiefiles/dotlottie-web https://monosnap.com/file/gSptGI3nsIgqlDoGSj7dw6ysCmPk4d

This is my HTML <canvas id="dotlottie-canvas" style="width: 100%; height: 100%" autoplay loop></canvas>

Previously I used https://github.com/dotlottie/player-component which is no longer maintained and it works perfectly
https://monosnap.com/file/Gm3AVZNcdqg4R1FzRixMdcFIC1YfNG

**Comment by moshbopayoneer** [comment]
Sure @theashraf 

Here is the JS:
`import { DotLottie } from "@lottiefiles/dotlottie-web";

document.addEventListener("DOMContentLoaded", (event) => {
  var isLottieExists = document.getElementsByTagName("canvas");

  const dotLottie = new DotLottie({
    autoplay: true,
    loop: true,
    canvas: document.querySelector("#dotlottie-canvas"),
    src: "/assets/svg-animations/minisite-header-left.lottie",
  });
});`

And this is the HTML:
`<canvas id="dotlottie-canvas" style="width: 100%;" autoplay loop></canvas>`

Tnx for your reply

**Comment by theashraf** [comment]
> And this is the HTML: `<canvas id="dotlottie-canvas" style="width: 100%;" autoplay loop></canvas>`

@moshbopayoneer Does the canvas element have a parent? If yes, what's the parent's size? Because currently with 100% width, the canvas dimensions are bounded to its parent, no?

**Comment by moshbopayoneer** [comment]
I understand but I have multiple animations + multiple widths of parent div's but I wish to show the animations at its original size with no connection to the parent div, like I'm doing now on dotlottie-player :)

**Comment by Fluccioni** [comment]
Hi @theashraf,
I think I'm facing the same issue ;

https://codepen.io/fluccioni/pen/jOoQbJO

I setup this small repro where I'd expected the canvas to have equals width & height attributes automatically regarding the animation's json `h` & `w` properties (both 500) but I don't understand why it has this aspect ratio of 2.

NB this is for the example, as @moshbopayoneer I can't give a fixed height to the canvas' parent.

Hoping the codepen can help, thanks !

**Comment by moshbopayoneer** [comment]
Yeah, this is the same issue, I can't see the animation in the original dimensions. Is there something that can be done here?
Parent div has various dimensions...also animations...I have 200+- animations, each animation has different dimensions... :)

**Comment by theashraf** [comment]
Gotcha, @moshbopayoneer @Fluccioni. A new method called `animation_size` has been added to the core dotLottie player. We plan to expose this method to users of dotlottie-web so they can retrieve the Lottie size as defined in the Lottie JSON file. With this size (width and height), users can update the canvas style to match the Lottie’s size after the animation is loaded.

We will update you once it's released.

Related https://github.com/LottieFiles/dotlottie-rs/issues/175

Hope this would solve your issue

**Comment by moshbopayoneer** [comment]
Good news! I'll wait :)

**Comment by theashraf** [comment]
The `animationSize` method has been added to dotlottie-web [v0.26.0](https://github.com/LottieFiles/dotlottie-web/releases/tag/%40lottiefiles%2Fdotlottie-web%400.26.0).

You can now get the Lottie animation size and update the canvas styles accordingly after the animation is loaded.

Here is a code example:

```javascript
dotLottie.addEventListener("load", () => {
  const animationSize = dotLottie.animationSize();
  
  canvas.style.width = `${animationSize.width}px`;
  canvas.style.height = `${animationSize.height}px`;
  
  dotLottie.resize(); // must call this method after the canvas is resized so dotLottie can resize its internal frame buffer size accordingly.
});
```

I hope this codepen achieves what you're looking for: https://codepen.io/lottiefiles/pen/xxNNGxE

**Comment by moshbopayoneer** [comment]
Ok, thanks! now the animation dimensions are good, but I see a small difference between dotlottie-player to the canvas
I placed both approaches on the same page and you can see that canvas (bottom animation) thing is missing the shadow on the small dots.
https://monosnap.com/file/2iTd7IXTD5qrMSYOsZXSFzgeISLgtf

How can I solve this issue?

**Comment by theashraf** [comment]
> I placed both approaches on the same page and you can see that canvas (bottom animation) thing is missing the shadow on the small dots.
> https://monosnap.com/file/2iTd7IXTD5qrMSYOsZXSFzgeISLgtf
> 
> How can I solve this issue?

@moshbopayoneer I believe this issue is related to the renderer used in the dotLottie player (thorvg). You might want to keep an eye on this issue or check out the suggested solution here: https://github.com/thorvg/thorvg/issues/2442

**Comment by theashraf** [comment]
Closing this as the canvas dimension issue has been fixed. @moshbopayoneer, feel free to open a new issue if you encounter any other problems. Thanks!
