### ISSUE TITLE
Mobile Safari hangs with "out of bounds memory access"

### ISSUE THREAD

**Issue by sir-oliver** [LottieFiles/dotlottie-web#292]
When using the latest Version 0.29 mobile Safari completely hangs.

`import { DotLottie } from "https://cdn.jsdelivr.net/npm/@lottiefiles/dotlottie-web@0.29.0/+esm";`

> [Error] RuntimeError: Out of bounds memory access (evaluating 'n(...u)')
> 	<?>.wasm-function[1069] (+esm:7:11371)
> 	<?>.wasm-function[706]
> 	<?>.wasm-function[146]
> 	<?>.wasm-function[1033]
> 	<?>.wasm-function[2364]
> 	<?>.wasm-function[3079]
> 	<?>.wasm-function[694]
> 	<?>.wasm-function[3076]
> 	<?>.wasm-function[2270]
> 	<?>.wasm-function[2457]
> 	<?>.wasm-function[1348]
> 	<?>.wasm-function[2282]
> 	<?>.wasm-function[2283]
> 	<?>.wasm-function[2983]
> 	<?>.wasm-function[694]
> 	<?>.wasm-function[2975]
> 	<?>.wasm-function[475]
> 	<?>.wasm-function[3229]
> 	<?>.wasm-function[3195]
> 	3195
> 	(anonymous function) (+esm:7:11371)
> 	_draw (+esm:7:39187)
> 
>

**Comment by theashraf** [comment]
@sir-oliver, can you provide the animation url you used?

**Comment by sir-oliver** [comment]
of course: https://busta.digital/assets/train.lottie

**Comment by sir-oliver** [comment]
you can test it here: https://busta.digital/train.html

**Comment by theashraf** [comment]
@sir-oliver, could you try dotlottie-web v0.29.1 ? It includes a fix for this issue

**Comment by sir-oliver** [comment]
bugfix works, thanks! 
test it here: https://busta.digital/train-0.29.1.html
