### ISSUE TITLE
When loading with dotlottie-web, the animation will be stretched

### ISSUE THREAD

**Issue by guide90** [LottieFiles/dotlottie-web#293]
## Overview

![image](https://github.com/user-attachments/assets/7f542bd2-b4ea-4565-b697-b57c9a55b793)

![image](https://github.com/user-attachments/assets/bd7d183d-886b-4d06-b97e-eb72b3db5389)

When I wrote it this way, the animated image was stretched when I opened the private window of the Chrome browser.

How to deal with this problem?

**Comment by theashraf** [comment]
@guide90 Which dotlottie-web version you're using ?

**Comment by theashraf** [comment]
@guide90 this should be fixed in v0.29.1
