### ISSUE TITLE
react player does not render first frame until window is resized

### ISSUE THREAD

**Issue by damnitrahul** [LottieFiles/dotlottie-web#296]
## Overview
I'm seeing a weird behavior while using`@lottiefiles/dotlottie-react`. I have an animation that will be triggered when in viewport and until it's played it should just show the first frame. 

But, it doesn't show up in the first frame after dotLottie file has been loaded and stays empty. It only renders the first frame if I resize the window. 

You can find the component code at https://github.com/LottieFiles/dotlottie-web/issues/286#issuecomment-2212408970
Here's a [loom](https://www.loom.com/share/20812733addc4542bf3451f154d6af4d?sid=5a0b4faf-e605-454b-9a0d-056610a05309) video for the behaviour 
...

## Consuming repo

> What repo were you working in when this issue occurred?
`@lottiefiles/dotlottie-react`

**Comment by theashraf** [comment]
@damnitrahul which dotlottie-react version you're using?

**Comment by damnitrahul** [comment]
`"@lottiefiles/dotlottie-react": "0.7.2"` @theashraf

**Comment by damnitrahul** [comment]
Tried with the latest `"@lottiefiles/dotlottie-react": "0.8.1"` - same results. 

One key thing to note is that it only happens when the player is off-screen when the page is loaded/refreshed. If I keep the player in viewport and try refreshing, it works as expected and shows the first frame. 
@theashraf

**Comment by damnitrahul** [comment]
This could be related to https://github.com/LottieFiles/dotlottie-web/issues/273

**Comment by damnitrahul** [comment]
Canvas is only rendered visible area in viewport.

![image](https://github.com/user-attachments/assets/f4b28d7a-b95e-4281-b390-90ce233fd443)

**Comment by theashraf** [comment]
Hi @damnitrahul, will address this issue in the next release by tomorrow

**Comment by theashraf** [comment]
@damnitrahul can you check out if dotlottie-react v0.8.3 fixes your issue

**Comment by damnitrahul** [comment]
@theashraf Yes! Thank you for addressing the issue. 🙏🏼
