### ISSUE TITLE
ReferenceError: Worker is not defined

### ISSUE THREAD

**Issue by bneeland** [LottieFiles/dotlottie-web#322]
## Overview

DotLottieReact, imported from @lottiefiles/dotlottie-react, within Next.js 14.2.5, results in the error:
```
ReferenceError: Worker is not defined
```

## Consuming repo

> What repo were you working in when this issue occurred?

dotlottie-web

## Labels

- [ ] Add the `Type: Bug` label to this issue.

**Comment by timuster** [comment]
+1

**Comment by rananajam1** [comment]
@timuster any luck fixing this issue or you opted to change the library?

**Comment by timuster** [comment]
@rananajam1 Please see #314 for how to make it work with Dynamic import... but as I said, it doesn't look as 'smooth'. There's a slight delay before the component loads (we deploy on Vercel cloud, so I doubt it's the hosting).

Unfortunately, it doesn't look like there are other libraries out there that support .lottie file extension (and are regularly maintained). Hence, at this point, we've decided to revert to `react-lottie` and use .json until this library can work without using the Dynamic import workaround.

**Comment by danjrwalsh** [comment]
I am getting this error as well with v0.4.9 of `@lottiefiles/dotlottie-vue` in a Nuxt 3.12.4 application.

**Comment by theashraf** [comment]
The issue has been fixed in the latest releases of dotlottie-web@0.30.3, dotlottie-react@0.8.8, and dotlottie-vue@0.4.10
