### ISSUE TITLE
Layout property not working

### ISSUE THREAD

**Issue by housemeow** [LottieFiles/dotlottie-web#323]
## Overview

After I apply the `layout` property to DotLottie object, the animation will disappear

## Consuming repo

> What repo were you working in when this issue occurred?

Here is the codepen link, yoiu you will see there are 2 canvas but only 1 shows. the different between them is `layout` property.
https://codepen.io/housemeow/pen/OJeQggr

## Labels

- [ ] Add the `Type: Bug` label to this issue.

**Comment by theashraf** [comment]
Hi @housemeow, It looks like the `layout` object is missing the `align` property.

<img width="949" alt="image" src="https://github.com/user-attachments/assets/885c5bc9-012d-4a60-8741-0cdb5009f2a9">

One enhancement we can implement on our end is to add default `fit` and `align` properties to the `layout` object if they are missing.

**Comment by housemeow** [comment]
thanks @theashraf reply!
cool! my animation shows!

does it mean 2 properties of layout object are required?

I can create a PR for that.

<img width="1048" alt="image" src="https://github.com/user-attachments/assets/f5bf5822-3a18-49d1-9414-fd594f81d989">

**Comment by theashraf** [comment]
Hi @housemeow, Yes, both are required, but we can make them optional if we have a default value to rely on.

Sure, feel free to contribute—this would be a valuable fix for those using the layout option.
