### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by glucka** [LottieFiles/dotlottie-web#328]
On Chrome 127.0.6533.99 Ubuntu 22.04
"@lottiefiles/dotlottie-web": "^0.30.3"
[hero.lottie.txt](https://github.com/user-attachments/files/16660717/hero.lottie.txt)

with all another files works fine

**Comment by theashraf** [comment]
Hi @glucka,

The .lottie file you provided contains an issue with the image assets. There are two PNG images included, but they are not valid PNG files.

Both images start with the following binary data:

```
75 AB 5A 8A
```

This does not match the expected PNG header:

```
89 50 4E 47
```

Here’s the content of the provided .lottie file:
<img width="671" alt="image" src="https://github.com/user-attachments/assets/dfcf59f1-6ae9-4380-95a7-95ed23de60da">

Could you please share how you created the .lottie file? If possible, providing the original Lottie JSON that you used for the conversion would be very helpful.

**Comment by glucka** [comment]
hi @theashraf, thanks for the quick answer! here the original json, convertet here: https://lottiefiles.com/tools/lottie-to-dotlottie
[animation.zip](https://github.com/user-attachments/files/16668787/animation.zip)

**Comment by theashraf** [comment]
@glucka seems a bug from the lottie-to-dotlottie converter, we're investigating and will let you know

**Comment by theashraf** [comment]
@glucka The file conversion works well now on LottieFiles; I've tested it. However, the issue still persists, so it’s clear that it originates from the dotLottie player side. I will investigate further and keep you updated.

Here is the converted file for reference: [optimized_m04rq00w.lottie.zip](https://github.com/user-attachments/files/16705326/optimized_m04rq00w.lottie.zip)

**Comment by ruoduan-hub** [comment]
I have the same problem. file 👇

[coin.json](https://github.com/user-attachments/files/16843027/coin.json)

**Comment by theashraf** [comment]
@glucka @ruoduan-hub fixed in dotlottie-web v0.35.0
