### ISSUE TITLE
Parcel build fails with version 0.30.3 – Constructing a Worker with a string literal is not supported

### ISSUE THREAD

**Issue by lkaisers** [LottieFiles/dotlottie-web#333]
## Overview

I just upgraded to version 0.30.3 of the dotlottie-web library and didn't change anything in my implementation that worked well with 0.30.2. Suddenly the build using Parcel fails.

![dotlottie-web-0 30 3-parcel-failure](https://github.com/user-attachments/assets/77015cef-9852-4327-b0f3-93e38a416079)

https://parceljs.org/languages/javascript/#web-workers

Possible help: https://chatgpt.com/share/5ad31f3d-f566-4a33-914b-73f86adbb9a4

## Consuming repo

> What repo were you working in when this issue occurred?

[https://www.npmjs.com/package/@lottiefiles/dotlottie-web/v/0.30.3](https://www.npmjs.com/package/@lottiefiles/dotlottie-web/v/0.30.3)

## Labels

- [ ] Add the `Type: Bug` label to this issue.

**Comment by theashraf** [comment]
@lkaisers There haven't been many changes in how we're creating the worker; we're still using the inlined worker file's base64 string to create it. 🤔

**Comment by theashraf** [comment]
related -> https://github.com/LottieFiles/dotlottie-web/blob/d4e0c035200a6eb9560dbc26f79876ae8a9289d9/packages/web/esbuild-plugins/plugin-inline-worker.cjs#L52

**Comment by theashraf** [comment]
@lkaisers It seems Parcel is not ok with the current worker instantiation approach. I found a workaround that involves creating the worker from a data URL instead of a string literal. I'll raise a patch for this in the next release. 

Thanks!!

**Comment by theashraf** [comment]
@lkaisers I've released a fix for this issue. Please test out dotlottie-web@v0.31.0. 
Thanks!!

**Comment by lkaisers** [comment]
@theashraf Works well again! Thank you for the quick release!
