### ISSUE TITLE
Post-build errors

### ISSUE THREAD

**Issue by ruoduan-hub** [LottieFiles/dotlottie-web#334]
## Overview
Post-build errors：426.2cce322dfd085e4d.js:21 Refused to connect to 'https://unpkg.com/@lottiefiles/dotlottie-web@0.30.2/dist/dotlottie-player.wasm' because it violates the document's Content Security Policy.
...

## Consuming repo

> What repo were you working in when this issue occurred?

...

## Labels

- [x] Add the `Type: Bug` label to this issue.

**Comment by theashraf** [comment]
We've discussed self-hosting the WASM file, which should resolve the CSP issue in your web app. You can find more details here: https://github.com/LottieFiles/dotlottie-web/discussions/198

**Comment by theashraf** [comment]
@ruoduan-hub, I'm closing this issue. Please let me know if the suggested solution in the linked discussion doesn't work for you. Thanks!
