### ISSUE TITLE
dotlottie-svelte,  too much CPU usage while playing animation.

### ISSUE THREAD

**Issue by Harabe-x** [LottieFiles/dotlottie-web#348]
## Issue
Hello, while using @lottiefiles/dotlottie-svelte I noticed that the CPU usage is way too high. While the animation is playing, Chrome's CPU usage increases to 50% and does not change until the animation is stopped. My processor is Intel Core i5-10400. For reference, typically chrome's CPU usage doesn't exceed 10%.

## How I use @lottiefiles/dotlottie-svelte
````
<script>
    import { DotLottieSvelte } from '@lottiefiles/dotlottie-svelte';
</script>

<div class="w-full h-full flex flex-col items-center justify-center">
    <div class=" w-9/12 h-full"  >
        <DotLottieSvelte  src="https://lottie.host/1b530b3a-fdab-42a9-86fb-e5f3150ffd6b/bSOd2Qvmxg.json" autoplay={true}  loop={true} ></DotLottieSvelte>
    </div>
    <div>
        <p class="text-xl text-center" > There are no images in this collection yet. </p>
    </div>
</div>
````

It is possible that I am simply using @lottiefiles/dotlottie-svelte incorrectly, if so please correct me.

CPU usage while animation is not playing 
![image](https://github.com/user-attachments/assets/41c6cf42-ffed-4c71-be11-41d2d52b9e80)
Vs 
CPU usage while the animation is playing
![image](https://github.com/user-attachments/assets/6742dad1-bda8-4bae-8196-bff78fa37cf8)

**Comment by theashraf** [comment]
Hi @Harabe-x 
When inspecting the DOM, What's the rendered canvas width and height ?

**Comment by Harabe-x** [comment]
580 x 300.  This problem also occurs when I preview what the animation looks like on the phone, 
when the animation is rendered on the phone the size is 250 x 130.

**Comment by theashraf** [comment]
@Harabe-x  
Here are a few things that might help:  
1. **Disable frame interpolation:** You can pass the `useFrameInterpolation={false}` prop to disable it.  
2. **Enable auto-resizing behavior:** This will automatically resize the internal frame buffer when the window is resized, improving rendering performance. You can enable it by passing the `renderConfig={{ autoResize: true }}` prop to the component.

If these options don’t resolve the issue, consider using `DotLottieWorker`. It offloads the rendering process to a web worker, freeing up the main thread to handle other tasks and potentially making the website smoother. The same resources will be used.

For more information, you can refer to the documentation here: https://developers.lottiefiles.com/docs/dotlottie-player/dotlottie-web/worker/
