### ISSUE TITLE
@lottiefiles/dotlottie-react v0.8.12 causes some elements to be inverted (v0.8.11 is fine)

### ISSUE THREAD

**Issue by EvHaus** [LottieFiles/dotlottie-web#351]
## Overview

After upgrading from v0.8.11 to v0.8.12 of `@lottiefiles/dotlottie-react` some elements in my Lottie animation are being rendered upside down (rotated 180deg). Rolling back to v0.8.11 fixes the issue.

### v0.8.11 output
![Kapture 2024-09-11 at 22 38 47](https://github.com/user-attachments/assets/f6098525-9963-44be-b004-6ae01bcc45a8)

### v0.8.12 output

![Kapture 2024-09-11 at 22 42 02](https://github.com/user-attachments/assets/c7890ff8-6130-44de-a881-add65ae93305)

Here is the lottie file I'm using:

https://app.reservesense.com/lottie/reportLoadingDone.lottie

## Consuming repo

N/A

## Labels

- [x] Add the `Type: Bug` label to this issue.

**Comment by EvHaus** [comment]
Looks like this is fixed in 0.9.0. Thank you!

**Comment by theashraf** [comment]
@EvHaus 
fixed in dotlottie-react v0.9.1

**Comment by EvHaus** [comment]
Confirmed. Thank you!
