### ISSUE TITLE
Unable to load json containing PNG sequence

### ISSUE THREAD

**Issue by Howlcn1997** [LottieFiles/dotlottie-web#404]
## Overview

When using PNG sequence in AE project, export it to json using bodymovin, and load it using dotlottie-web, dotlottie-web reports error "Failed to load animation data", But it works fine in airbnb/lottie-web.

You can check out my demo in codesandbox. [codesandbox](https://codesandbox.io/p/sandbox/y26qd9)

## Consuming repo

dotlottie-web: v0.36.1

**Comment by theashraf** [comment]
@Howlcn1997 the fix will land in next release of @lottiefiles/dotlottie-web@0.38.1
