### ISSUE TITLE
dotlottie-react layout

### ISSUE THREAD

**Issue by JakeLo123** [LottieFiles/dotlottie-web#431]
## Overview

It doesn't seem that [@lottiefiles/dotlottie-react](https://www.npmjs.com/package/@lottiefiles/dotlottie-react) supports the `layout` property that the `DotLottie` class does. Docs: [DotLottie React Properties](https://developers.lottiefiles.com/docs/dotlottie-player/dotlottie-react/properties/).

I'd like to be able to specify that the animation should maintain it's aspect ratio and cover the container. It doesn't seem that there's a way to configure `fit` or `align`.

My IDE does appear to acknowledge a `layout` prop on the `DotLottieReact` component, though it yields no change other than passing `layout="[object Object]"` to the rendered `canvas`.

I've noted that the layout property is in effect within the DotLottie web object as per [this issue](https://github.com/LottieFiles/dotlottie-web/issues/323).

## Consuming repo

Here's a reproducible example (apologies for I misspelling "reproducible" 😅): https://github.com/JakeLo123/lottie-reproducable

## Labels

- [x] Add the `Type: Bug` label to this issue.

**Comment by JakeLo123** [comment]
I'm able to get effects from `setLayout` on the `dotLottieRefCallback` if I do it within a `setTimeout`. Seems like a fishy way to achieve the result.

```tsx
import { DotLottieReact } from '@lottiefiles/dotlottie-react';

const App = () => {
  return (
    <div className="container">
      <DotLottieReact
        dotLottieRefCallback={(dotLottie) => {
          dotLottie?.setLayout({
            fit: 'cover',
            'align': [0, 0]
          })
          return dotLottie
        }}
        src="./asteroid-field.lottie"
        loop
        autoplay
      />
    </div>
  );
};
```

[Here's the branch](https://github.com/JakeLo123/lottie-reproducable/tree/fix-layout).

**Comment by theashraf** [comment]
@JakeLo123 Your approach is correct, but there may be a race condition if the dotLottie instance isn’t ready for interaction. Waiting for the ready event could help. I’ll also provide a fix in the next release and restore the layout prop.

```tsx
import { DotLottieReact } from '@lottiefiles/dotlottie-react';

const App = () => {
  return (
    <div className="container">
      <DotLottieReact
        dotLottieRefCallback={(dotLottie) => {
          dotLottie.addEventListener('ready', () => {
            dotLottie?.setLayout({
              fit: 'cover',
              align: [0, 0],
            });
          });
        }}
        src="./asteroid-field.lottie"
        loop
        autoplay
      />
    </div>
  );
};
```

**Comment by JakeLo123** [comment]
That's great!

It still doesn't handle resizing. Additionally, we are doing this kind of thing to handle that.

```ts
useEffect(() => {
    const handleResize = () => {
        dotLottieRef.current?.resize();
    };
    handleResize();
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
}, []);
```
